name: "Cachix push"
on:
  pull_request:
  push:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Add dependencies
        run: apt-get update && apt-get install -y sudo
      - uses: cachix/install-nix-action@v25
        with:
          nix_path: nixpkgs=channel:nixos-unstable
      - uses: cachix/cachix-action@v14
        env:
          USER: root
        with:
          name: suasuasuasuasua # cache name
          # # If you chose signing key for write access
          # signingKey: '${{ secrets.CACHIX_SIGNING_KEY }}'
          # If you chose API tokens for write access OR if you have a private cache
          authToken: "${{ secrets.CACHIX_AUTH_TOKEN }}"
      - name: Create post-build hook
        run: |
          cat > /post-build-hook << 'EOF'
          #!/bin/sh
          set -eu
          rm -rf /homeless-shelter
          [ -n "${OUT_PATHS:-}" ] && /root/.nix-profile/bin/cachix push suasuasuasuasua $OUT_PATHS || true
          EOF
          chmod +x /post-build-hook
      - name: Build the Nixvim presets
        run: |
          nix build --option max-jobs 1 \
            --option post-build-hook /post-build-hook \
            .#default .#minimal .#plain
